name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - Profile

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Update top followers
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python src/getTopFollowers.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest followers"
          git push
